#!/usr/bin/env python3
"""Start a run from a plain user brief without making the agent hand-build intake files.

This script is intentionally conservative. It registers the provided materials,
stores the exact brief text, and writes a transcription-first input_card.json.
It does not infer industry conclusions, peers, market data, or page arguments.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT_DIR = next(
    p for p in Path(__file__).resolve().parents
    if (p / "configs").is_dir() and (p / "scripts").is_dir()
)
ROLE_SCRIPT_DIRS = sorted(path for path in (ROOT_DIR / "scripts").iterdir() if path.is_dir())
QC_VALIDATOR_DIRS = sorted((ROOT_DIR / "scripts" / "qc" / "validators").glob("*"))
for path in [*ROLE_SCRIPT_DIRS, *QC_VALIDATOR_DIRS, ROOT_DIR / "scripts"]:
    text_path = str(path)
    if text_path not in sys.path:
        sys.path.insert(0, text_path)

from ingest_materials import ingest_materials  # type: ignore  # noqa: E402


CJK_RE = re.compile(r"[\u4e00-\u9fff]")


def _slug(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_\-\u4e00-\u9fff]+", "_", value.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned or "case"


def _read_brief(args: argparse.Namespace) -> str:
    if args.brief_text:
        return str(args.brief_text).strip()
    if args.brief_file:
        return Path(args.brief_file).read_text(encoding="utf-8").strip()
    raise SystemExit("Either --brief-text or --brief-file is required.")


def _default_run_dir(case_name: str, work_root: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return work_root / "runs" / _slug(case_name) / f"attempt_{stamp}"


def _detect_language(brief: str) -> tuple[str, str]:
    if CJK_RE.search(brief):
        return "zh-CN", "Chinese"
    return "en", "English"


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _mark_inline_brief_transcribed(extracts: dict[str, Any]) -> dict[str, Any]:
    for item in extracts.get("extracts", []):
        if not isinstance(item, dict):
            continue
        if item.get("file_path_or_url") == "inline_user_text":
            item["llm_extraction_status"] = "project_brief_transcribed_to_input_card"
            item["can_be_used_as_evidence"] = False
            item["claim_use_limitations"] = (
                "Project-specific brief transcribed into input_card.json. "
                "Do not use as external industry evidence."
            )
            item.setdefault("unknowns_or_conflicts", [])
    return extracts


def _build_input_card(
    *,
    brief: str,
    run_dir: Path,
    request_language: str,
    output_language: str,
    target_company: str,
    transaction_type: str,
    industry: str,
    subsector: str,
    geography: str,
) -> dict[str, Any]:
    user_paths = ["deal_context", "target_business_summary", "source_materials"]
    normalized_paths = [
        "engagement_context.stage",
        "engagement_context.audience",
        "engagement_context.objective",
        "engagement_context.tone",
        "language",
    ]
    for field_name, path_name in [
        (target_company, "target_company"),
        (transaction_type, "transaction_type"),
        (industry, "industry"),
        (subsector, "subsector"),
        (geography, "geography"),
    ]:
        if field_name:
            user_paths.append(path_name)
    return {
        "_provenance": {
            "_description": (
                "Generated by start_case_from_brief.py in transcription mode. "
                "Only explicit CLI fields and the exact user brief are populated."
            ),
            "request_language": request_language,
            "user_provided_paths": user_paths,
            "normalized_metadata_paths": normalized_paths,
        },
        "target_company": target_company,
        "transaction_type": transaction_type,
        "industry": industry,
        "subsector": subsector,
        "geography": geography,
        "language": output_language,
        "deal_context": brief,
        "engagement_context": {
            "stage": "pre_mandate_transaction_pitch",
            "audience": "potential_client_or_management",
            "objective": "demonstrate sector understanding first, then transaction-relevant judgment and selective target context where supported",
            "tone": "insightful_but_not_over_selling",
        },
        "target_business_summary": brief,
        "user_provided_target_facts": [],
        "known_risks_or_open_questions": [],
        "source_materials": [
            {
                "source_name": "User inline brief",
                "source_type": "project_specific_material",
                "source_access": "user_provided",
                "source_access_path": "inline_user_text",
                "source_date": "",
                "geography": geography,
                "fact_type": "factual",
                "confidence": "high",
                "scope": "target-level",
                "notes": "Exact user-provided brief saved in materials/user_brief.md and artifacts/material_texts/MAT-001.txt.",
            }
        ],
        "management_hypotheses": [],
        "peer_set": [],
        "must_cover_topics": [],
        "must_avoid_topics": [],
        "research_direction": {
            "_description": "Optional user-provided controls only. Planner-generated research choices belong in artifacts/formal_search_plan.json.",
            "priority_websites": [],
            "preferred_source_domains": [],
            "preferred_source_packs": [],
            "priority_topics": [],
            "peer_set": [],
            "avoid_topics": [],
            "avoid_sources": [],
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case-name", required=True)
    parser.add_argument("--brief-text")
    parser.add_argument("--brief-file")
    parser.add_argument("--run-dir", help="Existing or desired run directory. If omitted, runs/<case>/attempt_<timestamp> is created under --work-root.")
    parser.add_argument("--work-root", default=".", help="Work root used when --run-dir is omitted.")
    parser.add_argument("--file", action="append", default=[], help="Additional user material path.")
    parser.add_argument("--url", action="append", default=[], help="Additional user-provided URL.")
    parser.add_argument("--template-file", action="append", default=[], help="User PPT/POTX template path.")
    parser.add_argument("--target-company", default="")
    parser.add_argument("--transaction-type", default="")
    parser.add_argument("--industry", default="")
    parser.add_argument("--subsector", default="")
    parser.add_argument("--geography", default="")
    args = parser.parse_args()

    brief = _read_brief(args)
    work_root = Path(args.work_root).resolve()
    run_dir = Path(args.run_dir).resolve() if args.run_dir else _default_run_dir(args.case_name, work_root)
    artifacts = run_dir / "artifacts"
    materials = run_dir / "materials"
    artifacts.mkdir(parents=True, exist_ok=True)
    materials.mkdir(parents=True, exist_ok=True)
    (materials / "user_brief.md").write_text(brief + "\n", encoding="utf-8")

    manifest, extracts, source_classification = ingest_materials(
        brief_text=brief,
        files=list(args.file),
        template_files=list(args.template_file),
        urls=list(args.url),
        default_file_source_type="project_specific_material",
        default_url_source_type="manual_url_ingestion",
        output_material_manifest=artifacts / "material_manifest.json",
        output_material_extracts=artifacts / "material_extracts.json",
        output_source_classification=artifacts / "source_classification.json",
        dry_run=False,
    )
    extracts = _mark_inline_brief_transcribed(extracts)
    _write_json(artifacts / "material_extracts.json", extracts)
    _write_json(artifacts / "source_classification.json", source_classification)

    request_language, output_language = _detect_language(brief)
    input_card = _build_input_card(
        brief=brief,
        run_dir=run_dir,
        request_language=request_language,
        output_language=output_language,
        target_company=args.target_company.strip(),
        transaction_type=args.transaction_type.strip(),
        industry=args.industry.strip(),
        subsector=args.subsector.strip(),
        geography=args.geography.strip(),
    )
    _write_json(run_dir / "input_card.json", input_card)

    result = {
        "schema_version": "case_start_result_v1",
        "run_dir": str(run_dir),
        "material_manifest": str(artifacts / "material_manifest.json"),
        "material_extracts": str(artifacts / "material_extracts.json"),
        "source_classification": str(artifacts / "source_classification.json"),
        "input_card": str(run_dir / "input_card.json"),
        "template_registered": bool(args.template_file),
        "next_step": "Material role should review input_card transcription, then QC can run material/input validators.",
        "note": "This script does not infer industry conclusions or external evidence.",
        "material_count": len(manifest.get("materials", [])),
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
